github: [jimmy] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: jimmy_0 # Replace with a single Open Collective username
custom: https://www.patreon.com/krakbot # Replace with a single custom sponsorship URL
